package ee.schimke.composeai.rcconformance.engine

import androidx.compose.remote.core.CoreDocument
import ee.schimke.composeai.rcconformance.corpus.Check
import ee.schimke.composeai.rcconformance.corpus.Gold
import ee.schimke.composeai.rcconformance.corpus.Step
import ee.schimke.composeai.rcconformance.runner.ConformanceEngine
import ee.schimke.composeai.rcconformance.runner.ConformanceSession
import ee.schimke.composeai.rcconformance.runner.Observation
import ee.schimke.composeai.rcconformance.runner.UnsupportedStepKind
import ee.schimke.composeai.rcconformance.runner.toRgba
import ee.schimke.composeai.rcembedded.jvm.renderRemoteDocumentForInspection
import java.io.ByteArrayInputStream
import javax.imageio.ImageIO
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive

/**
 * The vendored AndroidX player, desktop-JVM cut — the **reference** lane.
 *
 * ### Why a second lane is worth the trouble
 *
 * A conformance score on its own cannot tell you where a disagreement lives. The corpus was
 * generated by AndroidX's own engine, so when the CMP player and a gold disagree there are two very
 * different explanations — the CMP player is wrong, or the gold encodes something specific to how
 * AndroidX does it — and a single lane cannot separate them.
 *
 * Running AndroidX's own player against the same corpus separates them. A gold this lane also fails
 * is a gold whose expectation does not survive contact with a second implementation of the thing
 * that produced it; a gold this lane passes and the CMP lane fails is ours to fix. That is the only
 * question this lane exists to answer, and it is why it is measured rather than trusted.
 *
 * ### What it observes
 *
 * `tree` comes from AndroidX's own laid-out `Component` graph — `getRootLayoutComponent()` and the
 * public geometry accessors — so the kinds are not translated into the corpus's vocabulary, they
 * *are* it. `raster` is the same render the `rc-compare` lanes use. `ops:*` is unavailable here and
 * reported as such: this module's document model is AndroidX's, whose operation list is not exposed
 * the way `:rc-player-protocol`'s is.
 *
 * ### What it cannot do, and why that is stated rather than hidden
 *
 * This is a **static-document** player. `RcPlayerJvm` is a faithful subset that renders a document
 * once; it has no gesture dispatch, no clock control and no animation stepping. Every step kind
 * past `paint`/`resize` therefore throws [UnsupportedStepKind] and the runner fails those checks as
 * `STEP_NOT_RUN` — which is the truth about this lane, and much more useful than a reference that
 * silently no-ops its way to a flattering number.
 */
public class AndroidxJvmEngine : ConformanceEngine {
  override val name: String = "androidx-jvm"

  override val version: String =
    CoreDocument.MAJOR_VERSION.toString() +
      "." +
      CoreDocument.MINOR_VERSION +
      "." +
      CoreDocument.PATCH_VERSION

  override fun <T> withSession(gold: Gold, block: (ConformanceSession) -> T): T =
    block(AndroidxJvmSession(gold))
}

private class AndroidxJvmSession(private val gold: Gold) : ConformanceSession {
  private val bytes = gold.documentBytes()

  private var width = gold.parameters.intOrDefault("width", 400)
  private var height = gold.parameters.intOrDefault("height", 400)
  private val density = gold.parameters.floatOrDefault("density", 1f)

  private var rendered: Rendered? = null

  private class Rendered(val document: CoreDocument, val png: ByteArray)

  override fun execute(step: Step, onCapture: (String) -> Unit) {
    when (step.kind) {
      "paint" -> render()
      "resize" -> {
        width = step.int("width", width)
        height = step.int("height", height)
        render()
      }
      "settle" -> Unit
      // Everything else needs a running player: a gesture to dispatch, a clock to move, a frame to
      // advance. This cut renders a static document, so saying so is the honest answer — see the
      // class note.
      else -> throw UnsupportedStepKind(step.kind)
    }
  }

  private fun render() {
    val result = renderRemoteDocumentForInspection(bytes, width, height, density)
    rendered = Rendered(result.document, result.png)
  }

  override fun observe(check: Check): Observation =
    when (check.key) {
      // Not `tree`: see the class note. The geometry exists but was never assigned, and a tree of
      // zeroes would be diffed as a layout disagreement rather than read as the unpopulated field
      // it is.
      "raster" -> raster()
      "ops:component_count" ->
        rendered?.let { Observation.Value(JsonPrimitive(it.document.componentCount)) }
          ?: Observation.NotImplemented
      else -> Observation.NotImplemented
    }

  private fun raster(): Observation {
    val png = rendered?.png ?: return Observation.NotImplemented
    val decoded =
      ImageIO.read(ByteArrayInputStream(png)) ?: error("could not decode the ${gold.name} frame")
    val rgba = decoded.toRgba()
    return Observation.Raster(rgba.width, rgba.height, rgba.rgba)
  }
}

private fun JsonObject.intOrDefault(key: String, fallback: Int): Int =
  (this[key] as? JsonPrimitive)?.content?.toDoubleOrNull()?.toInt() ?: fallback

private fun JsonObject.floatOrDefault(key: String, fallback: Float): Float =
  (this[key] as? JsonPrimitive)?.content?.toFloatOrNull() ?: fallback
