package ee.schimke.composeai.rcconformance.engine

import androidx.compose.remote.core.CoreDocument
import androidx.compose.remote.core.operations.layout.Component
import ee.schimke.composeai.rcconformance.corpus.Check
import ee.schimke.composeai.rcconformance.corpus.Gold
import ee.schimke.composeai.rcconformance.corpus.Step
import ee.schimke.composeai.rcconformance.runner.ConformanceEngine
import ee.schimke.composeai.rcconformance.runner.ConformanceSession
import ee.schimke.composeai.rcconformance.runner.Observation
import ee.schimke.composeai.rcconformance.runner.UnsupportedStepKind
import ee.schimke.composeai.rcconformance.runner.toRgba
import ee.schimke.composeai.rcembedded.jvm.RcJvmLaidOutDocument
import ee.schimke.composeai.rcembedded.jvm.layoutRemoteDocumentForInspection
import ee.schimke.composeai.rcembedded.jvm.renderRemoteDocumentForInspection
import java.io.ByteArrayInputStream
import java.io.File
import javax.imageio.ImageIO
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.buildJsonArray
import kotlinx.serialization.json.buildJsonObject

/**
 * The vendored AndroidX player, desktop-JVM cut — the **reference** lane.
 *
 * ### Why a second lane is worth the trouble
 *
 * A conformance score on its own cannot tell you where a disagreement lives. The corpus was
 * generated by AndroidX's own engine, so when the CMP player and a gold disagree there are two very
 * different explanations — the CMP player is wrong, or the gold encodes something specific to how
 * AndroidX does it — and a single lane cannot separate them.
 *
 * Running AndroidX's own player against the same corpus separates them. A gold this lane also fails
 * is a gold whose expectation does not survive contact with a second implementation of the thing
 * that produced it; a gold this lane passes and the CMP lane fails is ours to fix. That is the only
 * question this lane exists to answer, and it is why it is measured rather than trusted.
 *
 * ### What it observes
 *
 * `tree` comes from AndroidX's own laid-out `Component` graph — `getRootLayoutComponent()` and the
 * public geometry accessors — so the kinds are not translated into the corpus's vocabulary, they
 * *are* it. `raster` is the same render the `rc-compare` lanes use. `ops:*` is unavailable here and
 * reported as such: this module's document model is AndroidX's, whose operation list is not exposed
 * the way `:rc-player-protocol`'s is.
 *
 * The tree needs a **second pass**, not the render's. `RcPlayerJvm` is a Compose renderer over
 * `CoreDocument`: it walks the operations and draws them, and never runs AndroidX's own measure, so
 * the `Component` geometry the corpus asserts is left unassigned. `CoreDocument.paint` is where
 * AndroidX measures and places, so the tree comes from running that against a measure-only paint
 * context (`MeasuringPaintContext`) — drawing dropped, text measured for real by the same skiko
 * stack the raster uses. The pass is lazy: a gold with no `tree` check never pays for it.
 *
 * When that pass reports it could not measure wrapped text, the tree is withheld as
 * `PROBE_NOT_IMPLEMENTED` rather than emitted. A reference lane's fabricated geometry is worse than
 * no reference: it would mark a real CMP disagreement as *shared* and bury the finding.
 *
 * ### The corpus font
 *
 * 174 of the 252 golds declare `harness.text_metrics: ahem`, meaning the corpus measured *and drew*
 * them with the Ahem font answering for every family. This lane pins it too, for both passes, which
 * is required setup rather than a refinement (`CONFORMANCE_FORMAT.md` §2.2): Ahem's glyphs are
 * solid 1em squares, so a run's pixels and metrics depend only on where it was placed — the thing
 * the corpus asserts — and not on glyph outlines, which two text engines may legitimately disagree
 * about. Measured against the platform default instead, every text-bearing gold carries a permanent
 * error floor from outline mismatch alone, and a gold failing for that reason is indistinguishable
 * from a real disagreement.
 *
 * A `native` gold is left on the host's own fonts, because that is what `native` means.
 *
 * **The pin reaches the measure pass and not the render.** Three of the four canvas text operations
 * resolve through the skiko seam this pins; `DrawText` builds a Compose `TextStyle` and is drawn by
 * Compose text, whose face comes from a `FontFamily.Resolver` — and that interface is `sealed`, so
 * a scene-level substitution is not available. Overriding it needs the pinned family threaded to
 * `toTextStyle` through the platform-neutral drawing code, which is a change in the shared player
 * rather than here.
 *
 * So this lane's `tree` is measured in Ahem and its `raster` is not. That is a strict improvement
 * on neither being — no gold regressed and two text golds lost diffs — but it bounds what the
 * raster column means for text golds, and it is the largest remaining lever on this lane: 49 of its
 * 164 failing golds fail on `raster` **alone**, and 17 of those are golds the CMP player also
 * fails, so they would join the work list rather than the shared bucket.
 *
 * ### What it cannot do, and why that is stated rather than hidden
 *
 * This is a **static-document** player. `RcPlayerJvm` is a faithful subset that renders a document
 * once; it has no gesture dispatch, no clock control and no animation stepping. Every step kind
 * past `paint`/`resize` therefore throws [UnsupportedStepKind] and the runner fails those checks as
 * `STEP_NOT_RUN` — which is the truth about this lane, and much more useful than a reference that
 * silently no-ops its way to a flattering number.
 */
public class AndroidxJvmEngine(specDir: File) : ConformanceEngine {
  /**
   * The corpus's own Ahem face, read once.
   *
   * Required rather than optional: a missing font would silently score every text-bearing gold
   * against the platform default, and the lane would look like it had measured something.
   */
  private val ahemTtf: ByteArray =
    File(specDir, "fonts/Ahem.ttf").let { file ->
      require(file.isFile) {
        "the corpus font is missing at ${file.absolutePath} — every text-bearing gold would be " +
          "scored against the platform default face, which measures differently and makes the " +
          "text results meaningless"
      }
      file.readBytes()
    }

  override val name: String = "androidx-jvm"

  override val version: String =
    CoreDocument.MAJOR_VERSION.toString() +
      "." +
      CoreDocument.MINOR_VERSION +
      "." +
      CoreDocument.PATCH_VERSION

  override fun <T> withSession(gold: Gold, block: (ConformanceSession) -> T): T =
    block(AndroidxJvmSession(gold, ahemTtf.takeIf { gold.textMetrics == "ahem" }))
}

private class AndroidxJvmSession(private val gold: Gold, private val pinnedFontTtf: ByteArray?) :
  ConformanceSession {
  private val bytes = gold.documentBytes()

  private var width = gold.parameters.intOrDefault("width", 400)
  private var height = gold.parameters.intOrDefault("height", 400)
  private val density = gold.parameters.floatOrDefault("density", 1f)

  private var rendered: Rendered? = null

  /**
   * The laid-out document, measured on demand and discarded whenever a step moves the viewport.
   *
   * Lazy because it is a second full pass over the document: a gold that asserts no `tree` — every
   * canvas gold, for one — must not pay for one.
   */
  private var laidOut: RcJvmLaidOutDocument? = null

  private class Rendered(val document: CoreDocument, val png: ByteArray)

  override fun execute(step: Step, onCapture: (String) -> Unit) {
    when (step.kind) {
      "paint" -> render()
      "resize" -> {
        width = step.int("width", width)
        height = step.int("height", height)
        render()
      }
      "settle" -> Unit
      // Everything else needs a running player: a gesture to dispatch, a clock to move, a frame to
      // advance. This cut renders a static document, so saying so is the honest answer — see the
      // class note.
      else -> throw UnsupportedStepKind(step.kind)
    }
  }

  private fun render() {
    val result =
      renderRemoteDocumentForInspection(
        bytes,
        width,
        height,
        density,
        pinnedFontTtf = pinnedFontTtf,
      )
    rendered = Rendered(result.document, result.png)
    // A resize invalidates the layout as surely as it invalidates the frame.
    laidOut = null
  }

  override fun observe(check: Check): Observation =
    when (check.key) {
      "tree" -> tree()
      "raster" -> raster()
      "ops:component_count" ->
        rendered?.let { Observation.Value(JsonPrimitive(it.document.componentCount)) }
          ?: Observation.NotImplemented
      else -> Observation.NotImplemented
    }

  /**
   * AndroidX's laid-out component graph, in the corpus's own tree vocabulary (§4.3).
   *
   * Withheld entirely when the layout pass could not measure wrapped text — see the class note.
   */
  private fun tree(): Observation {
    val laidOut = laidOut ?: layout().also { laidOut = it }
    if (laidOut.measuredComplexText) return Observation.NotImplemented
    val root = laidOut.document.rootLayoutComponent ?: return Observation.NotImplemented
    return Observation.Value(
      buildJsonArray {
        fun walk(component: Component, depth: Int) {
          add(component.toTreeJson(depth))
          component.list.forEach { child -> if (child is Component) walk(child, depth + 1) }
        }
        walk(root, 0)
      }
    )
  }

  /**
   * One node, keyed the way the comparator matches: by component id.
   *
   * `kind` is the component's own class name because that *is* the corpus's vocabulary — the golds
   * were generated from this graph — so nothing is translated here and nothing can drift. `x` and
   * `y` are already parent-relative on AndroidX's side, which is what §4.3 asks for.
   */
  private fun Component.toTreeJson(depth: Int): JsonObject = buildJsonObject {
    put("id", JsonPrimitive(componentId))
    put("kind", JsonPrimitive(this@toTreeJson::class.java.simpleName))
    put("depth", JsonPrimitive(depth))
    put("x", JsonPrimitive(x))
    put("y", JsonPrimitive(y))
    put("width", JsonPrimitive(width))
    put("height", JsonPrimitive(height))
    put("isGone", JsonPrimitive(mVisibility == GONE))
    put(
      "visibility",
      JsonPrimitive(
        when (mVisibility) {
          GONE -> "GONE"
          INVISIBLE -> "INVISIBLE"
          else -> "VISIBLE"
        }
      ),
    )
  }

  private fun layout(): RcJvmLaidOutDocument =
    layoutRemoteDocumentForInspection(bytes, width, height, density, pinnedFontTtf = pinnedFontTtf)

  private fun raster(): Observation {
    val png = rendered?.png ?: return Observation.NotImplemented
    val decoded =
      ImageIO.read(ByteArrayInputStream(png)) ?: error("could not decode the ${gold.name} frame")
    val rgba = decoded.toRgba()
    return Observation.Raster(rgba.width, rgba.height, rgba.rgba)
  }
}

/** AndroidX visibility: 0 gone, 1 visible, 2 invisible but measured. */
private const val GONE = 0

private const val INVISIBLE = 2

private fun JsonObject.intOrDefault(key: String, fallback: Int): Int =
  (this[key] as? JsonPrimitive)?.content?.toDoubleOrNull()?.toInt() ?: fallback

private fun JsonObject.floatOrDefault(key: String, fallback: Float): Float =
  (this[key] as? JsonPrimitive)?.content?.toFloatOrNull() ?: fallback
